apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis-operator
spec:
  targetNamespace: redis-operator
  install:
    createNamespace: true
  chart:
    spec:
      chart: redis-operator
      version: 3.2.7
      sourceRef:
        kind: HelmRepository
        name: redis-operator
  interval: 1m0s
  releaseName: redis-operator
