apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres-operator
spec:
  targetNamespace: postgres-operator
  install:
    createNamespace: true
  chart:
    spec:
      chart: postgres-operator
      version: 1.9.0
      sourceRef:
        kind: HelmRepository
        name: postgres-operator
  interval: 1m0s
  releaseName: postgres-operator
