apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: k8s-harbor
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/SovereignCloudStack/k8s-harbor
  ref:
    branch: postgres-test
