apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  targetNamespace: cert-manager
  chart:
    spec:
      chart: cert-manager
      version: v1.17.1
      sourceRef:
        kind: HelmRepository
        name: cert-manager
  interval: 1m0s
  releaseName: cert-manager
  install:
    createNamespace: true
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    installCRDs: true
