apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: postgres-operator
spec:
  interval: 1m0s
  url: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
