apiVersion: v1
data:
  config.yaml: |
    chartmuseum:
      enabled: true
      replicas: 2
    trivy:
      replicas: 2
    notary:
      enabled: true
      server:
        replicas: 2
      signer:
        replicas: 2
    portal:
      replicas: 2
    core:
      replicas: 2
    jobservice:
      replicas: 2
      jobLoggers:
      - database
    registry:
      replicas: 2
    cache:
      enabled: true
    metrics:
      enabled: true
    internalTLS:
      enabled: true
    expose:
      type: ingress
      tls:
        enabled: true
        certSource: secret
        secret:
          secretName: harbor-crt
          notarySecretName: notary-crt
      ingress:
        hosts:
          core: harbor.test.dnation.cloud
          notary: harbor-notary.test.dnation.cloud
        className: nginx
        harbor:
          annotations:
            cert-manager.io/issuer: letsencrypt
        notary:
          annotations:
            cert-manager.io/issuer: letsencrypt
    externalURL: https://harbor.test.dnation.cloud
    database:
      type: external
      external:
        host: "postgresql"
        username: "harbor"
        coreDatabase: "registry"
        notaryServerDatabase: "notaryserver"
        notarySignerDatabase: "notarysigner"
        # generated by postgres-operator
        existingSecret: "harbor-postgresql-auth"
        sslmode: "require"
    redis:
      type: external
      external:
        addr: "rfs-redisfailover:26379"
        sentinelMasterSet: "mymaster"
        # generated by redis-secret.bash
        existingSecret: "harbor-redis-auth"
    persistence:
      persistentVolumeClaim:
        trivy:
          size: 10Gi
      imageChartStorage:
        type: swift
        swift:
          authurl: https://api.gx-scs.sovereignit.cloud:5000/v3
          # application credentials support, see https://github.com/distribution/distribution/pull/3403
          # username and password are populated via swift-secret.bash
          container: registry
          region: RegionOne
          tenantid: 602778bad3d3470cbe58c4f7611e8eb7
          domain: d500924
kind: ConfigMap
metadata:
  name: harbor-config
  namespace: default
