apiVersion: v1
data:
  config.yaml: |
    fullnameOverride: harbor-harbor
    trivy:
      enabled: true
      replicas: 2
    portal:
      replicas: 2
    core:
      replicas: 2
    jobservice:
      replicas: 2
      jobLoggers:
      - database
    registry:
      replicas: 2
    metrics:
      enabled: true
    cache:
      enabled: true
    expose:
      type: ingress
      tls:
        enabled: true
        certSource: secret
        secret:
          secretName: harbor-harbor-ingress
      ingress:
        hosts:
          core: registry.scs.community
        className: nginx
        harbor:
          annotations:
            cert-manager.io/issuer: letsencrypt
    externalURL: https://registry.scs.community
    database:
      type: internal
    redis:
      type: internal
    persistence:
      enabled: true
      persistentVolumeClaim:
        database:
          size: 256Gi
        redis:
          size: 128Gi
        trivy:
          size: 256Gi
      imageChartStorage:
        type: s3
        s3:
          regionendpoint: https://api.gx-scs.sovereignit.cloud:8080
          # accesskey and secretkey are populated via s3-secret.bash
          bucket: registry
          region: RegionOne
kind: ConfigMap
metadata:
  name: harbor-config
  namespace: default
