apiVersion: v1
data:
  config.yaml: |
    persistence:
      persistentVolumeClaim:
        registry:
          size: 1Ti
        jobservice:
          size: 64Gi
        database:
          size: 256Gi
        redis:
          size: 128Gi
        trivy:
          size: 256Gi
    expose:
      type: ingress
      tls:
        enabled: true
        secret:
          secretName: le-harbor
      ingress:
        hosts:
          core: registry.scs.community
        annotations:
          nginx.ingress.kubernetes.io/ssl-redirect: 'true'
          kubernetes.io/ingress-class: 'nginx'
          cert-manager.io/issuer: 'letsencrypt'
    externalURL: https://registry.scs.community
kind: ConfigMap
metadata:
  name: harbor-config
  namespace: default
