apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
spec:
  targetNamespace: ingress-nginx
  install:
    createNamespace: true
  chart:
    spec:
      chart: ingress-nginx
      version: 4.5.2
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
  interval: 1m0s
  releaseName: ingress-nginx
  values:
    controller:
      kind: DaemonSet
      service:
        type: NodePort
        nodePorts:
          http: 32080
          https: 32443
