apiVersion: v1
data:
  config.yaml: |
    expose:
      type: clusterIP
      tls:
        enabled: false
    externalURL: http://harbor.default.svc
kind: ConfigMap
metadata:
  name: harbor-config
  namespace: default
