apiVersion: v1
data:
  config.yaml: |
    trivy:
      enabled: true
    metrics:
      enabled: true
    persistence:
      enabled: true
    externalURL: http://harbor.default.svc
kind: ConfigMap
metadata:
  name: harbor-config
