apiVersion: v1
data:
  config.yaml: |
    
    nginx:
      image:
        repository: goharbor/nginx-photon
        tag: v2.0.2
    
    portal:
      image:
        repository: goharbor/harbor-portal
        tag: v2.0.2

    core:
      image:
        repository: goharbor/harbor-core
        tag: v2.0.2
    
    jobservice:
      image:
        repository: goharbor/harbor-jobservice
        tag: v2.0.2
    
    registry:
      registry:
        image:
          repository: goharbor/registry-photon
          tag: v2.0.2

      controller:
        image:
          repository: goharbor/harbor-registryctl
          tag: v2.0.2
    
    chartmuseum:
      enabled: true
      image:
        repository: goharbor/chartmuseum-photon
        tag: v2.0.2

    clair:
      enabled: true
      clair:
        image:
          repository: goharbor/clair-photon
          tag: v2.0.2

      adapter:
        image:
          repository: goharbor/clair-adapter-photon
          tag: v2.0.2
    
    trivy:
      enabled: true
      image:
        repository: goharbor/trivy-adapter-photon
        tag: v2.0.2
    
    notary:
      enabled: true
      server:
        image:
          repository: goharbor/notary-server-photon
          tag: v2.0.2

      signer:
        image:
          repository: goharbor/notary-signer-photon
          tag: v2.0.2
    
    database:
      type: internal
      internal:
        image:
          repository: goharbor/harbor-db
          tag: v2.0.2
    
    redis:
      type: internal
      internal:
        image:
          repository: goharbor/redis-photon
          tag: v2.0.2
    
kind: ConfigMap
metadata:
  name: harbor-base-config
