apiVersion: v1
data:
  config.yaml: |
    chartmuseum:
      enabled: false
    trivy:
      enabled: true
    notary:
      enabled: false
    database:
      type: internal
    redis:
      type: internal
kind: ConfigMap
metadata:
  name: harbor-base-config
  namespace: default
