apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: harbor-helm
spec:
  interval: 1m
  url: https://github.com/goharbor/harbor-helm.git
  ref:
    tag: v1.6.0
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor
spec:
  interval: 1m
  chart:
    spec:
      chart: .
      sourceRef:
        kind: GitRepository
        name: harbor-helm
  valuesFrom:
  - kind: ConfigMap
    name: harbor-base-config
    valuesKey: config.yaml
  - kind: ConfigMap
    name: harbor-config
    valuesKey: config.yaml
