apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor
spec:
  chart:
    spec:
      chart: harbor
      version: 1.12.1
      sourceRef:
        kind: HelmRepository
        name: harbor-helm
  interval: 1m0s
  releaseName: harbor
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  valuesFrom:
  - kind: ConfigMap
    name: harbor-base-config
    valuesKey: config.yaml
  - kind: ConfigMap
    name: harbor-config
    valuesKey: config.yaml
    optional: true
  - kind: Secret
    name: harbor-secrets
    valuesKey: values.yaml
    optional: true
