---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: postgres-operator
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: flux-system
  sourceRef:
    kind: GitRepository
    name: k8s-harbor
  path: "./postgres/operator"
  prune: true
  healthChecks:
  - apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    name: postgres-operator
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: postgres-cluster
  namespace: flux-system
spec:
  dependsOn:
  - name: postgres-operator
  interval: 10m
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: k8s-harbor
  path: "./postgres/cluster"
  prune: true
