apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: postgresql
spec:
  teamId: "harbor"
  volume:
    size: 10Gi
  numberOfInstances: 2
  users:
    # {namespace}.{username} when enable_cross_namespace_secret is true
    harbor:
    - createdb
  databases:
    registry: harbor
    notaryserver: harbor
    notarysigner: harbor
  postgresql:
    version: "15"
