name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  KUBECONFIG: k3s.yaml

jobs:
  integration-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v2
    - name: Spawn Kubernetes Cluster
      uses: yellowmegaman/k3s-gha@master
      with:
        k3s_tag: v1.18.6-k3s1
        kubectl_version: v1.18.6
    - name: Setup fluxctl
      with:
        version: v0.8.1
    - name: Setup fluxctl
      uses: fluxcd/fluxctl-action@v1.19.0
    - name: Install Flux
      run: |
        kubectl create ns flux
        fluxctl install \
        --git-path=envs/ci-testing \
        --git-branch=${GITHUB_REF#refs/heads/} \
        --git-readonly=true \
        --registry-disable-scanning=true \
        --git-email=invalid@scs.community \
        --git-url=https://github.com/$GITHUB_REPOSITORY.git \
        --manifest-generation=true \
        --namespace=flux | kubectl apply -f -
    - name: Verify Flux Installation
      run: kubectl -n flux rollout status deploy/flux --timeout=1m
    - name: Force fluxctl sync with git
      env:
        FLUX_FORWARD_NAMESPACE: flux
      run: fluxctl sync
    - name: Wait for service to be Ready
      run: ./test/wait
    - name: Check if service is working as expected
      run: ./test/test
    - name: Get fluxcd logs
      if: ${{ always() }}
      run: kubectl logs -n flux deploy/flux
    - name: Fetch helm-operator logs if present
      if: ${{ always() }}
      run: |
        kubectl get deploy -n flux helm-operator && kubectl logs -n flux deploy/helm-operator || echo 'helm-operator not present'
